--- #YAML:1.0
name: SVN-Look
abstract: A caching wrapper aroung the svnlook command.
version: 0.27
author: Gustavo Chaves <gnustavo@cpan.org>
license: perl
generated_by: Gustavo Chaves
distribution_type: module
requires:
  perl: 5.008
  Test::More: 0
  File::Spec::Functions: 0
build_requires:
  URI::file: 0
resources:
  license: http://dev.perl.org/licenses/
  homepage: http://code.google.com/p/svn-look/
  repository: http://svn-look.googlecode.com/svn/trunk/
meta-spec:
  version: 1.3
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
