--- #YAML:1.0
# http://module-build.sourceforge.net/META-spec.html
name: SVN-Look
abstract: A caching wrapper aroung the svnlook command.
version: 0.16
author: Gustavo Chaves <gnustavo@cpan.org>
license: perl
generated_by: Gustavo Chaves
distribution_type: module
requires:
  Test::More: 0
  File::Spec::Functions: 0
resources:
  license: http://dev.perl.org/licenses/
